### ISSUE TITLE
Room crashes if a player leaves after a match

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#47] opened 2021-01-27 19:34 UTC
If you play a match and someone leaves the room after the match ended, the whole room (usually excluding the one who left so far) will crash

**Comment by Davingi** [comment] 2021-01-27 21:05
Bug is reproducable when the player leaving the room has a chat bubble

**Comment by Davingi** [comment] 2021-01-27 22:29
Not closing it until it's confirmed, that this bug is truly fixed.

**Comment by sstokic-tgm** [comment] 2021-01-28 01:09
Refer this as an addition: 47c1967

**Comment by Velucy** [comment] 2021-01-28 17:53
Didn't encounter this bug anymore so far. Will report if anything in this direction comes up

**Comment by elmuty24** [comment] 2021-01-28 17:55
![image](https://user-images.githubusercontent.com/58943878/106178697-dd32dd00-6178-11eb-8210-26ceda5f8742.png)

celebrate even didnt start the game

**Comment by elmuty24** [comment] 2021-01-28 17:56
and the bug of celebrating even lose is still alive

**Comment by Davingi** [comment] 2021-02-02 19:13
Closing this issue since the bug doesn't seem to occur anymore.

**Closed by Davingi** 2021-02-02 19:13 UTC
Labels: bug
