### ISSUE TITLE
Item Re-Status

### ISSUE THREAD

**Issue by toddymon** [sstokic-tgm/JFTSE#89] opened 2021-03-21 11:00 UTC
Can we fix this item for re-status of character.
For now we use this then that wasn't happening.
![image](https://user-images.githubusercontent.com/26331241/111902264-32031d80-8a6f-11eb-843e-b5295ab794eb.png)

**Comment by sstokic-tgm** [comment] 2021-03-21 11:23
Duplicate of #24
Item behaviour items are further down in the prio list, they will come after the basic/general game functionality is brought back 👍

**Closed by sstokic-tgm** 2021-03-21 11:23 UTC
Labels: duplicate

**Comment by toddymon** [comment] 2021-03-21 12:01
Thanks. *-*
